[package]
name = "cloudcheck"
version = "0.1.0"
edition = "2021"

[dependencies]
radixtarget = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "cloudcheck"
path = "src/main.rs"

[lib]
name = "cloudcheck"
path = "src/lib.rs"

